Numpy is a third party package that specializes in scientific and technical computing.

In [3]:
import numpy as np

# 1D array

In [4]:
a = np.array([range(3)])
a

array([[0, 1, 2]])

In [5]:
type(a)

numpy.ndarray

#2D array

In [8]:
b = np.array([range(3),range(3,6)])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.shape

(2, 3)

# reshape

In [10]:
c = np.array(range(6))
c

array([0, 1, 2, 3, 4, 5])

In [11]:
c1 = c.reshape((2,3))
c1

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
c2 = c1.reshape((3,2))
c2

array([[0, 1],
       [2, 3],
       [4, 5]])

# dtype

In [13]:
d = np.array(range(6))
d.dtype

dtype('int64')

In [14]:
d.astype(np.float16)

array([0., 1., 2., 3., 4., 5.], dtype=float16)

# index and slice

In [15]:
e = np.array(range(6))
e

array([0, 1, 2, 3, 4, 5])

In [16]:
e[1]

1

⇒　Can be treated like a normal array.

In [17]:
e[1:]

array([1, 2, 3, 4, 5])

In [18]:
e[:-1]

array([0, 1, 2, 3, 4])

⇒　You can use a colon to specify a range.

In [19]:
f = np.array([range(3),range(3,6)])
f

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
f[1,:]

array([3, 4, 5])

In [21]:
f[:,1]

array([1, 4])

# Data reassignment

In [26]:
g = np.array([range(3),range(3,6)])
g

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
g[1,2] = 6
g

array([[0, 1, 2],
       [3, 4, 6]])

In [28]:
g[0,:] = 7
g

array([[7, 7, 7],
       [3, 4, 6]])

# arange


Like the range function, the arange function can be used to generate NumPy arrays.

In [29]:
h = np.array(range(5))
h

array([0, 1, 2, 3, 4])

In [30]:
i = np.arange(5)
i

array([0, 1, 2, 3, 4])

# random

In [33]:
j = np.random.random((3,2))
j

array([[0.80307746, 0.99287998],
       [0.84311483, 0.9366271 ],
       [0.18605786, 0.853852  ]])

The random function generates a different sequence of numbers each time it is executed, but a fixed random sequence of numbers can be generated by specifying a seed value.

In [35]:
np.random.seed(42)
k = np.random.random((3,2))
k

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

# Create an array of identical elements

In [36]:
np.zeros((2))

array([0., 0.])

In [37]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.full((2,2), np.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

# concatenate・split

In [40]:
l = np.arange(3)
m = np.arange(3)

In [41]:
n = np.concatenate([l,m])
n

array([0, 1, 2, 0, 1, 2])

In [42]:
o = np.zeros((3,3))
p = np.ones((3,3))

In [43]:
q = np.concatenate([o,p])
q

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
r = np.concatenate([o,p], axis=1)
r

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [45]:
first, second = np.hsplit(r, [2])
first

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
second

array([[0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.]])

## Transpose

In [47]:
second.T

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Generate grid data

In [48]:
s = np.arange(3)
t = np.arange(2,4)
u,v = np.meshgrid(s, t)

In [49]:
u

array([[0, 1, 2],
       [0, 1, 2]])

In [50]:
v

array([[2, 2, 2],
       [3, 3, 3]])