Numpy is a third party package that specializes in scientific and technical computing.

In [43]:
import numpy as np

# 1D array

In [ ]:
a = np.array([range(3)])
a

array([[0, 1, 2]])

In [ ]:
type(a)

numpy.ndarray

#2D array

In [ ]:
b = np.array([range(3),range(3,6)])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.shape

(2, 3)

# reshape

In [ ]:
c = np.array(range(6))
c

array([0, 1, 2, 3, 4, 5])

In [ ]:
c1 = c.reshape((2,3))
c1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
c2 = c1.reshape((3,2))
c2

array([[0, 1],
       [2, 3],
       [4, 5]])

# dtype

In [ ]:
d = np.array(range(6))
d.dtype

dtype('int64')

In [ ]:
d.astype(np.float16)

array([0., 1., 2., 3., 4., 5.], dtype=float16)

# index and slice

In [ ]:
e = np.array(range(6))
e

array([0, 1, 2, 3, 4, 5])

In [ ]:
e[1]

1

⇒　Can be treated like a normal array.

In [ ]:
e[1:]

array([1, 2, 3, 4, 5])

In [ ]:
e[:-1]

array([0, 1, 2, 3, 4])

⇒　You can use a colon to specify a range.

In [ ]:
f = np.array([range(3),range(3,6)])
f

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
f[1,:]

array([3, 4, 5])

In [ ]:
f[:,1]

array([1, 4])

# Data reassignment

In [ ]:
g = np.array([range(3),range(3,6)])
g

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
g[1,2] = 6
g

array([[0, 1, 2],
       [3, 4, 6]])

In [ ]:
g[0,:] = 7
g

array([[7, 7, 7],
       [3, 4, 6]])

# arange


Like the range function, the arange function can be used to generate NumPy arrays.

In [ ]:
h = np.array(range(5))
h

array([0, 1, 2, 3, 4])

In [ ]:
i = np.arange(5)
i

array([0, 1, 2, 3, 4])

# random

In [ ]:
j = np.random.random((3,2))
j

array([[0.80307746, 0.99287998],
       [0.84311483, 0.9366271 ],
       [0.18605786, 0.853852  ]])

The random function generates a different sequence of numbers each time it is executed, but a fixed random sequence of numbers can be generated by specifying a seed value.

In [ ]:
np.random.seed(42)
k = np.random.random((3,2))
k

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])

# Create an array of identical elements

In [ ]:
np.zeros((2))

array([0., 0.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.full((2,2), np.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

# concatenate・split

In [ ]:
l = np.arange(3)
m = np.arange(3)

In [ ]:
n = np.concatenate([l,m])
n

array([0, 1, 2, 0, 1, 2])

In [ ]:
o = np.zeros((3,3))
p = np.ones((3,3))

In [ ]:
q = np.concatenate([o,p])
q

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
r = np.concatenate([o,p], axis=1)
r

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
first, second = np.hsplit(r, [2])
first

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
second

array([[0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.]])

## Transpose

In [ ]:
second.T

array([[0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Generate grid data

In [ ]:
s = np.arange(3)
t = np.arange(2,4)
u,v = np.meshgrid(s, t)

In [ ]:
u

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
v

array([[2, 2, 2],
       [3, 3, 3]])

## Universal Functions

In [15]:
w = [[-2, -1],
     [1, 2]]
np.abs(w)

array([[2, 1],
       [1, 2]])

In [16]:
np.sin(w)

array([[-0.90929743, -0.84147098],
       [ 0.84147098,  0.90929743]])

In [17]:
np.cos(w)

array([[-0.41614684,  0.54030231],
       [ 0.54030231, -0.41614684]])

## Broadcasting

In [44]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [45]:
x+10

array([11, 12, 13])

In [46]:
x*10

array([10, 20, 30])

In [47]:
y = x[:, np.newaxis]
y

array([[1],
       [2],
       [3]])

In [48]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [49]:
z = np.array([[1,2],
     [3,4]])
z

array([[1, 2],
       [3, 4]])

In [50]:
z - np.mean(z)

array([[-1.5, -0.5],
       [ 0.5,  1.5]])

In [51]:
z**2

array([[ 1,  4],
       [ 9, 16]])

In [52]:
x@y

array([14])

In [53]:
z < np.mean(z)

array([[ True,  True],
       [False, False]])

In [54]:
np.sum(z < np.mean(z))

2

In [55]:
np.any(z < np.mean(z))

True

In [56]:
np.all(z < np.mean(z))

False

In [60]:
np.allclose(x,x)

True

In [61]:
np.allclose(x,y)

False

In [62]:
np.allclose(x,y,atol=3)

True

In [63]:
z.sum()

10

In [64]:
np.sum(z)

10